[package]
name = "library"
version = "0.1.0"
authors = ["Steve McCown <smccown@anonyome.com>"]
license = "Apache version 2.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = "0.22"
# includes the 'thiserror' crate.
thiserror = "1.0"

[lib]
name = "library"
crate-type = ["cdylib"]

[build-dependencies]
uniffi_build = "0.22"

